global_frame: odom
robot_base_frame: base_link
update_frequency: 20.0
publish_frequency: 20.0
publish_voxel_map: true
static_map: false
rolling_window: true
width: 6.0
height: 6.0
resolution: 0.025

map_type: voxel
origin_z: 0.0
z_resolution: 1
z_voxels: 32
unknown_threshold: 10
mark_threshold: 1

transform_tolerance: 0.3
obstacle_range: 2.5
max_obstacle_height: 1.0
min_obstacle_height: -0.2 # front laser is at approx. -0.03
raytrace_range: 3.0
cost_scaling_factor: 10.0
lethal_cost_threshold: 100

obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.25, 0.18], [-0.25, 0.18], [-0.25,-0.18], [0.25,-0.18]]
inflation_radius: 0.1

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_laser_front_link, data_type: LaserScan, topic: scan_front, marking: true, clearing: true}
